version: '3.8'

services:
  backend:
    build: ./backend
    container_name: serverless-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/serverless
      - PORT=5000
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongodb
    networks:
      - serverless-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: "1000:989"  # Use current user ID and Docker group ID

  mongodb:
    image: mongo:latest
    container_name: serverless-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - serverless-network
    restart: unless-stopped

  # This service will be used to build and store function images
  function-registry:
    image: registry:2
    container_name: function-registry
    ports:
      - "5001:5000"
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - serverless-network
    restart: unless-stopped

networks:
  serverless-network:
    driver: bridge

volumes:
  mongodb_data:
  registry_data: